routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminSkillController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\WeatherController;
use App\Http\Controllers\AdminMainController;
use App\Http\Controllers\AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


Route::middleware(['auth', 'user.check'])->group(function () {
    Route::prefix('profile')->group(function () {
        Route::get('/auth/google', [UserController::class, 'googleRedirect'])->name('auth.google');
        Route::get('/auth/google/callback', [UserController::class, 'loginWithGoogle']);
        Route::get('/', [UserController::class, 'profile'])->name('profile');
        Route::post('/update', [UserController::class, 'update'])->name('profile.update');
    });
    Route::get('/home{category_id?}', [SkillController::class, 'index'])->name('skills')->where('category_id', '[0-9]+');
    Route::post('/skills/search', [SkillController::class, 'search'])->name('skills.search');
    Route::get('/weather', [WeatherController::class, 'currentWeather'])->name('weather');
    Route::get('/cv', [SkillController::class, 'showCV'])->name('cv');
    Route::get('/skills/invoice_pdf', [SkillController::class, 'invoicePdf'])
        ->name('skills.invoicepdf');
    //Route::get('/admin', [App\Http\Controllers\SkillController::class, 'index'])->name('admin')->middleware('auth.type:user');

});
Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(
        function () {
            Route::get('/', [AdminMainController::class, 'index'])->name('admin');
            Route::resource('skills', AdminSkillController::class);
            Route::resource('categories', AdminCategoryController::class);
            Route::resource('users', AdminUserController::class);
        });
});


//Route::get('/home',[ \App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
//Route::get('/admin',[ \App\Http\Controllers\HomeController::class, 'admin'])->name('admin')->middleware('auth')


//        Route::post('/', [\App\Http\Controllers\UserController::class, 'update'])->name('profile.update');
//        Route::get('/user', [\App\Http\Controllers\UserController::class, 'show'])->name('user.show');
//        Route::get('/invoice_pdf', [\App\Http\Controllers\UserController::class, 'invoicePdf'])
//            ->name('user.invoicepdf');

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Skill extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'skills';

    /**
     * The table associated with the model.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'image',
        'level',
        'category_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'users');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function getCreatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }

    public function getUpdatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }


}

app/Http/Controllers/AdminSkillController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skill;
use App\Services\CategoryService;
use App\Services\SkillService;
use App\Http\Requests\SkillUpdateRequest;
use App\Http\Requests\SkillStoreRequest;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;


class AdminSkillController extends Controller
{

    /**
     * @var SkillService
     */
    private $skills;
    /**
     * @var CategoryService
     */
    private $categories;

    public function __construct(SkillService $skills, CategoryService $categories)
    {
        $this->skills = $skills;
        $this->categories = $categories;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('admin_skill.index', ["skills" => $this->skills->all()
        ]);
    }
    //

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin_skill.create',
            [

                "categories" => $this->categories->all(),
            ]);
    }

    /**
     * Store a newly created resource in storage.
     * @param SkillStoreRequest $request
     */
    public function store(SkillStoreRequest $request)
    {
        $skill = $this->skills->create($request->all());
        return redirect()->route('skills.show', ["skill" => $skill->id])->withSuccess('Skill #' . $skill->id . " " . 'was created!');
    }

    /**
     * Display the specified resource.
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|Application
     */
    public function show($id)
    {
        return view('admin_skill.show',
            ["skills" => $this->skills->findById($id)
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|Factory|View|Application
     */
    public function edit($id)
    {
        return view('admin_skill.edit',
            [

                "skills" => $this->skills->findById($id),
                "categories" => $this->categories->all(),
            ]);
    }

    /**
     * Update the specified resource in storage.
     * @param SkillUpdateRequest $request
     * @param Skill $skill
     * @return
     */
    public function update(SkillUpdateRequest $request, Skill $skill)
    {


        $this->skills->update($skill->id, $request->except(['_method', '_token']));
        return redirect()->route('skills.show', ["skill" => $skill->id])->withSuccess('Skill #' . $skill->id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     * @param $id
     * @param Skill $skill
     * @return
     */
    public function destroy($id)
    {
        $this->skills->destroy($id);
        return redirect()->route('skills.index')->withSuccess('Skill #' . $id . 'was deleted!');
    }
}

resources/views/admin_skill/create.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('skills.store') }}">

        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="name">Create Skill</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror"
                               name="name" id="name"  value="{{ old('name') }}">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="level">Level</label>
                        <input type="number" name="level" id="level"
                               class="form-control @error('level') is-invalid @enderror" min="1"
                               value="{{ old('level') }}">
                        @error('level')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="categories">Skill Category</label>
                        <select name="category_id"
                                class="form-control custom-select @error('category_id') is-invalid @enderror">
                            <option value="">Choose category</option>
                            {{--                            <?php var_dump(old('category_id'));  ?>--}}
                            {{--                            {{ var_dump($categories[0]->id) }}--}}
                            @foreach($categories as $category)
                                <option @if(old('category_id') && $category->id == old('category_id'))
                                        selected
                                        @endif
                                        value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <a href="{{ route('skills.index') }}" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Create" class="btn btn-outline-dark">
                </form>

@endsection

resources/views/admin_skill/edit.blade.php
@extends('adminlte::page')

@section('content')

    <form method="POST" action="{{ route('skills.update', ["skill" => $skills->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="inputName">Skill Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="inputName"
                               value=" {{old('name') ?? $skills->name }} ">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="level">Level</label>
                        <input type="number" name="level" id="level"
                               class="form-control @error('level') is-invalid @enderror"
                               min="1" max="5" value="{{ $skills->level }}">
                        @error('level')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="categories">Skill Category</label>
                        <select name="category_id"
                                class="form-control custom-select @error('category_id') is-invalid @enderror">
                            <option value="">Choose category</option>
{{--                            <?php var_dump(old('category_id'));  ?>--}}
{{--                            {{ var_dump($categories[0]->id) }}--}}
                            @foreach($categories as $category)
                                <option @if(old('category_id') && $category->id == old('category_id'))
                                        selected
                                        @elseif (empty(old('category_id')) && $category->id === $skills->category->id)
                                            selected
                                        @endif
                                        value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('category_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <input type="submit" value="Save Changes" class="btn btn-outline-dark">
                </form>
                    <a href="{{ route('skills.index', ["skill" => $skills->all()]) }}" type="button"
                       class="btn btn-outline-danger">Back</a>


@stop

resources/views/admin_skill/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="skills" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Name
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Category ID
            </th>
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Image
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Level
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Created at
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Updated at
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Actions
        </tr>
        </thead>
        <tbody>
        @foreach($skills as $skill)
            <tr role="row">
                <td>{{ $skill->name }}</td>
                <td>{{ $skill->category_id}}</td>
                <td>{{ $skill->image}}</td>
                <td>{{ $skill->level}}</td>
                <td>{{ $skill->created_at }}</td>
                <td>{{ $skill->updated_at }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('skills.show', ["skill" => $skill->id]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('skills.edit', ["skill" => $skill->id]) }}" type="button"
                           class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('skills.destroy', ["skill" => $skill->id]) }}">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="delete"  class="btn btn-info">
                        </form>
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop
@section('js')
    <script>
        $(function () {
            $('#skills').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@stop

resources/views/admin_skill/show.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <div class="row">
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> </strong>
                <p class="text">
                    <strong>     Skill name: </strong> {{ $skills->name }}
                </p>
                <hr>
                <p class="text">
                    <strong>  Category name: </strong> {{ $skills->category->name }}
                </p>

                <hr>

                <strong><i class="fa fa-map-marker margin-r-5"></i> Image</strong>

                <p class="text-muted">{{ $skills->image }}</p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Level is:  {{ $skills->level }}</strong>
                <hr>


                <strong><i class="fa fa-pencil margin-r-5"></i> Time</strong>

                <p> Created at {{ $skills->created_at }} </p>
                <p> Updatet at {{ $skills->updated_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>
            <a href="{{ route('skills.edit', ["skill" => $skills->id]) }}" type="button"
               class="btn btn-outline-info">Edit</a>
            <a href="{{ route('skills.index', ["skill" => $skills->all()]) }}" type="button"
               class="btn btn-outline-warning">Back to the list</a>
        </div>




@stop