routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminSkillController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\WeatherController;
use App\Http\Controllers\AdminMainController;
use App\Http\Controllers\AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


Route::middleware(['auth', 'user.check'])->group(function () {
    Route::prefix('profile')->group(function () {
        Route::get('/auth/google', [UserController::class, 'googleRedirect'])->name('auth.google');
        Route::get('/auth/google/callback', [UserController::class, 'loginWithGoogle']);
        Route::get('/', [UserController::class, 'profile'])->name('profile');
        Route::post('/update', [UserController::class, 'update'])->name('profile.update');
    });
    Route::get('/home{category_id?}', [SkillController::class, 'index'])->name('skills')->where('category_id', '[0-9]+');
    Route::post('/skills/search', [SkillController::class, 'search'])->name('skills.search');
    Route::get('/weather', [WeatherController::class, 'currentWeather'])->name('weather');
    Route::get('/cv', [SkillController::class, 'showCV'])->name('cv');
    Route::get('/skills/invoice_pdf', [SkillController::class, 'invoicePdf'])
        ->name('skills.invoicepdf');
    //Route::get('/admin', [App\Http\Controllers\SkillController::class, 'index'])->name('admin')->middleware('auth.type:user');

});
Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(
        function () {
            Route::get('/', [AdminMainController::class, 'index'])->name('admin');
            Route::resource('skills', AdminSkillController::class);
            Route::resource('categories', AdminCategoryController::class);
            Route::resource('users', AdminUserController::class);
        });
});


//Route::get('/home',[ \App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
//Route::get('/admin',[ \App\Http\Controllers\HomeController::class, 'admin'])->name('admin')->middleware('auth')


//        Route::post('/', [\App\Http\Controllers\UserController::class, 'update'])->name('profile.update');
//        Route::get('/user', [\App\Http\Controllers\UserController::class, 'show'])->name('user.show');
//        Route::get('/invoice_pdf', [\App\Http\Controllers\UserController::class, 'invoicePdf'])
//            ->name('user.invoicepdf');

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Skill extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'skills';

    /**
     * The table associated with the model.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'image',
        'level',
        'category_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'users');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function getCreatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }

    public function getUpdatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }


}

app/Http/Controllers/AdminUserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUserProfileRequest;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use App\Models\UserSkill;
use App\Services\LangService;
use App\Services\SkillService;
use App\Services\UserSkillService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Services\UserService;


class AdminUserController extends Controller
{

    /**
     * @var UserService
     */
    private $users;

    /**
     * @var LangService
     */
    private $langs;

    /**
     * @var SkillService
     */
    private $skills;

    /**
     * @var UserSkillService
     */
    private $userSkills;

    public function __construct(UserService $users, LangService $langs, SkillService $skills, UserSkillService $userSkills )
    {
        $this->users = $users;
        $this->langs = $langs;
        $this->skills = $skills;
        $this->userSkills = $userSkills;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        /** @var UserSkill $userSkills */
        return view('admin_user.index', [
            "users" => $this->users->getNotAdminUsers(),
            "skills" => $this->userSkills->all(),
        ]);

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
       return view('admin_user.create',
        [
            "langs" => $this->langs->all(),
            "skills" => $this->skills->all(),
        ]
    );
    }

    /**
     * Store a newly created resource in storage.
     * @param UserStoreRequest $request
     */
    public function store(UserStoreRequest $request) :RedirectResponse
    {
        /** @var User $user */
        $user = $this->users->create($request->all());

        return redirect()->route('users.show', ["user" => $user])->withSuccess('User #' . $user->id . 'was created!');
    }

    /**
     * Display the specified resource.
     * @param $id
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function show($id)
    {
        return view('admin_user.show',
            [
                "user" => $this->users->findById($id)
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param $id
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function edit($id)
    {
        return view('admin_user.edit',
            [

                "user" => $this->users->findById($id),
                "langs" => $this->langs->all(),
                "skills" => $this->skills->all(),
            ]);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param User $user
     * @return
     */
    public function update(Request $request, User $user)
    {
        //dd($user->id);
        $this->users->update($user->id, $request->except(['_method', '_token']));
        return redirect()->route('users.show', ["user" => $user->id])->withSuccess('User #' . $user->id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     * @param string $id
     */
    public function destroy($id)
    {
        $this->users->destroy($id);
        return redirect()->route('users.index')->withSuccess('User #' . $id . 'was deleted!');
    }
}

resources/views/admin_user/create.blade.php
@extends('adminlte::page')

@section('content')

    <form method="POST" action="{{ route('users.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="inputName">Create new User</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="inputName"
                               value="{{old('name')}}">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email"
                               class="form-control @error('email') is-invalid @enderror"
                               value="{{old('email')  }}">
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">User Language</label>
                        <select name="lang"
                                class="form-control custom-select @error('lang') is-invalid @enderror">
                            <option value="">Choose language</option>
                            @foreach($langs as $lang)
                                <option @if(old('lang') && $lang->short_name == old('lang'))
                                        selected
                                        @endif
                                        value="{{ $lang->short_name }}">{{ $lang->full_name }}</option>
                            @endforeach
                        </select>
                        @error('lang')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">User Status</label>
                        <select name="status"
                                class="form-control custom-select @error('status') is-invalid @enderror">
                            <option
                                @if(old('status') && "active" == old('status'))
                                selected
                                @endif
                                value="active">Active </option>
                            <option
                                @if(old('status') && "not active" == old('status'))
                                selected>
                                @endif
                                value="not active">Not Active </option>
                        </select>
                        @error('status')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password"
                               class="form-control @error('password') is-invalid @enderror" value="">
                        @error('password')
                        <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Confirm Password</label>
                        <input type="password" name="password_confirmation" id="password_confirmation"
                               class="form-control @error('password_confirmation') is-invalid @enderror"
                               value="">
                    </div>

                    <input type="submit" value="Create" class="btn btn-outline-dark">
                </form>
            </div>
        </div>
    </form>
{{--                    <a href="{{ route('admin.user.index', ["user" => $user->all()]) }}" type="button"--}}
{{--                       class="btn btn-outline-danger">Back</a>--}}


@stop

resources/views/admin_user/edit.blade.php
@extends('adminlte::page')

@section('content')

    <form method="POST" action="{{ route('users.update', ["user" => $user->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label for="inputName">User Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="inputName"
                               value=" {{old('name') ?? $user->name }} ">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email"
                               class="form-control @error('email') is-invalid @enderror"
                               value="{{old('email') ?? $user->email }}">
                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">User Language</label>
                        <select name="lang"
                                class="form-control custom-select @error('lang') is-invalid @enderror">
                            <option value="">Choose language</option>
                            @foreach($langs as $lang)
                                <option @if(old('lang') && $lang->short_name == old('lang'))
                                        selected
                                        @elseif (empty(old('lang')) && $lang->short_name === $user->lang->short_name)
                                            selected
                                        @endif
                                        value="{{ $lang->short_name }}">{{ $lang->full_name }}</option>
                            @endforeach
                        </select>
                        @error('lang')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="inputStatus">User Status</label>
                        <select name="status"
                                class="form-control custom-select @error('status') is-invalid @enderror">
                            <option
                                @if(old('status') && "active" == old('status'))
                                selected
                                @elseif (empty(old('status')) && "active" === $user->status)
                                selected
                                @endif
                                value="active">Active </option>
                            <option
                                @if(old('status') && "not active" == old('status'))
                                selected
                                @elseif (empty(old('status')) && "not active" === $user->status)
                                selected
                                @endif
                                value="not active">Not Active </option>
                        </select>
                        @error('status')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <input type="submit" value="Save Changes" class="btn btn-outline-dark">
                </form>
                    <a href="{{ route('users.index', ["user" => $user->all()]) }}" type="button"
                       class="btn btn-outline-danger">Back</a>


@stop

resources/views/admin_user/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="users" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Name
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Email
            </th>
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Type
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Status
            </th>
           {{-- <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >User Skills
            </th>--}}
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Language
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Actions
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr role="row">
                <td>{{ $user->name }}</td>
                <td>{{ $user->email}}</td>
                <td>{{ $user->type}}</td>
                <td>{{ $user->status}}</td>
                <td>
                    @if(!empty( $user->lang->full_name))
                        {{ $user->lang->full_name }}
                        @endif
                </td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('users.show', ["user" => $user->id]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('users.edit', ["user" => $user->id]) }}" type="button"
                           class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('users.destroy', ["user" => $user->id]) }}">
                            @method('DELETE')
                            @csrf
                            <input type="submit" value="delete"  class="btn btn-info">
                        </form>
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop
@section('js')
    <script>
        $(function () {
            $('#skills').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@stop

resources/views/admin_user/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> {{ $user->name }} </strong>

                <p class="text-muted">
                    ID is # {{ $user->id }}
                </p>

                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Email </strong>
                <li>
                    {{ $user->email }}
                </li>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> User Lang </strong>
                <li>
                    {{ $user->lang->full_name }}
                </li>
                <hr>

                <strong><i class="fa fa-pencil margin-r-5"></i> Created at </strong>

                <p> {{ $user->created_at }} </p>
                <hr>


                <strong><i class="fa fa-pencil margin-r-5"></i> Updatet at</strong>


                <p>  {{ $user->updated_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>
            <a href="{{ route('users.index') }}" class="btn btn-secondary">To all list</a>
            <a href="{{ route('users.edit', ["user" => $user->id]) }}" type="button" class="btn btn-info">Edit</a>
        </div>
    </div>






@stop