routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminSkillController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SkillController;
use App\Http\Controllers\WeatherController;
use App\Http\Controllers\AdminMainController;
use App\Http\Controllers\AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', function () {
    return view('welcome');
});


Route::middleware(['auth', 'user.check'])->group(function () {
    Route::prefix('profile')->group(function () {
        Route::get('/auth/google', [UserController::class, 'googleRedirect'])->name('auth.google');
        Route::get('/auth/google/callback', [UserController::class, 'loginWithGoogle']);
        Route::get('/', [UserController::class, 'profile'])->name('profile');
        Route::post('/update', [UserController::class, 'update'])->name('profile.update');
    });
    Route::get('/home{category_id?}', [SkillController::class, 'index'])->name('skills')->where('category_id', '[0-9]+');
    Route::post('/skills/search', [SkillController::class, 'search'])->name('skills.search');
    Route::get('/weather', [WeatherController::class, 'currentWeather'])->name('weather');
    Route::get('/cv', [SkillController::class, 'showCV'])->name('cv');
    Route::get('/skills/invoice_pdf', [SkillController::class, 'invoicePdf'])
        ->name('skills.invoicepdf');
    //Route::get('/admin', [App\Http\Controllers\SkillController::class, 'index'])->name('admin')->middleware('auth.type:user');

});
Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(
        function () {
            Route::get('/', [AdminMainController::class, 'index'])->name('admin');
            Route::resource('skills', AdminSkillController::class);
            Route::resource('categories', AdminCategoryController::class);
            Route::resource('users', AdminUserController::class);
        });
});


//Route::get('/home',[ \App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
//Route::get('/admin',[ \App\Http\Controllers\HomeController::class, 'admin'])->name('admin')->middleware('auth')


//        Route::post('/', [\App\Http\Controllers\UserController::class, 'update'])->name('profile.update');
//        Route::get('/user', [\App\Http\Controllers\UserController::class, 'show'])->name('user.show');
//        Route::get('/invoice_pdf', [\App\Http\Controllers\UserController::class, 'invoicePdf'])
//            ->name('user.invoicepdf');

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Skill extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'skills';

    /**
     * The table associated with the model.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'image',
        'level',
        'category_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'users');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function getCreatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }

    public function getUpdatedAtAttribute($value)
    {
        return date("Y-m-d", strtotime($value));
    }


}

app/Http/Controllers/AdminCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Services\CategoryService;
use App\Http\Requests\CategoryUpdateRequest;
use App\Http\Requests\CategoryStoreRequest;
use Illuminate\Validation\Rule;

class AdminCategoryController extends Controller
{
    /**
     * @var CategoryService
     */
    private $categories;

    public function __construct(CategoryService $categories)
    {
        $this->categories = $categories;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('admin_category.index', ["categories" => $this->categories->all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin_category.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     */
    public function store(CategoryStoreRequest $request)
    {

        $category = $this->categories->create($request->all());
        return redirect()->route('categories.show', ["category" => $category->id])->withSuccess('Category #' . $category->id . " " . 'was created!');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        return view('admin_category.show',
        ["category" => $this->categories->findById($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        return view('admin_category.edit',
            [

                "category" => $this->categories->findById($id),
                ]);
    }

    /**
     * Update the specified resource in storage.
     * @param CategoryUpdateRequest $request
     * @param Category $category
     * @return
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        $this->categories->update($category->id, $request->except(['_method', '_token']));
        return redirect()->route('categories.show', ["category" => $category->id])->withSuccess('Category #' . $category->id . 'was updated!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $this->categories->destroy($id);
        return redirect()->route('categories.index')->withSuccess('Category #' . $id . 'was deleted!');
    }
}

resources/views/admin_category/create.blade.php
@extends('adminlte::page')

@section('content')

    <form   method="POST" action="{{ route('categories.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Create Category</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                           id="inputName"
                           value=" {{old('name') }} ">
                    @error('name')
                    <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
        @enderror
                </div>
            </div>
        </div>
 <a href="#" class="btn-btn-secondarary"> Cancel</a>
    <input type="submit" value="Create" class="btn btn-outline-dark">
    </form>

@stop

@section('js')
@stop

resources/views/admin_category/edit.blade.php
@extends('adminlte::page')

@section('content')

    <form method="POST" action="{{ route('categories.update', ["category" => $category->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="form-group">
                        <label >Category</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                               id="inputName"
                               value=" {{old('name') ?? $category->name }} ">
                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror

                    <input type="submit" value="Save Changes" class="btn btn-outline-dark">
                </form>
                    <a href="{{ route('categories.index', ["category" => $category->all()]) }}" type="button"
                       class="btn btn-outline-danger">Back</a>


@stop

resources/views/admin_category/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <table id="skills" class="table table-bordered table-hover dataTable" role="grid"
           aria-describedby="example2_info">
        <thead>
        <tr role="row">
            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending"
            >Name
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Category ID
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Created at
            </th>
            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
            >Actions
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr role="row">
                <td>{{ $category->name }}</td>
                <td>{{ $category->id }}</td>
                <td>{{ $category->created_at }}</td>

                <td>
                    <div class="btn-group">
                        <a href="{{ route('categories.show', ["category" => $category->id]) }}" type="button"
                           class="btn btn-info">View</a>
                        <a href="{{ route('categories.edit', ["category" => $category->id]) }}" type="button"
                           class="btn btn-info">Edit</a>
{{--                        --}}{{--<form method="POST" action="{{ route('category.destroy', ["category" => $category->id]) }}">--}}
{{--                            @method('DELETE')--}}
{{--                            @csrf--}}
{{--                            <input type="submit" value="delete"  class="btn btn-info">--}}
{{--                        </form>--}}
                    </div>
                </td>
        @endforeach
        </tbody>
    </table>

@stop
@section('js')
    <script>
        $(function () {
            $('#categories').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@stop

resources/views/admin_category/show.blade.php
@extends('adminlte::page')

@section('content')
    @include('partials.alerts')
    <div class="row">
        <div class="col-md-12">
            <div class="box-body">
                <strong><i class="fa fa-book margin-r-5"></i> </strong>
                <p class="text">
                    <strong>     Category name: </strong> {{ $category->name }} #{{ $category->id }}
                </p>

                <hr>

                <strong><i class="fa fa-map-marker margin-r-5"></i> Image</strong>

                <strong><i class="fa fa-pencil margin-r-5"></i> Time</strong>

                <p> Created at {{ $category->created_at }} </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Description</strong>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
            </div>
            <a href="{{ route('categories.edit', ["category" => $category->id]) }}" type="button"
               class="btn btn-outline-info">Edit</a>
            <a href="{{ route('categories.index', ["category" => $category->all()]) }}" type="button"
               class="btn btn-outline-warning">Back to the list</a>
        </div>




@stop